Pakhai viktor hw7
katemalash/Rv-056.PythonCore pull request #67
Opened 2021-01-15 13:31 UTC by ViktorPakhai

2021-01-19 20:42 UTC, katemalash requested changes
Please improve task 3.

2021-01-19 20:42 UTC, katemalash commented on pakhai/HW7/task_1_hw7.py
> +print("Original string:   ", data_string, "\nString after removing:  ", newstring)
Good way.

2021-01-19 20:42 UTC, katemalash commented on pakhai/HW7/task_2_hw7.py
> +print("Task 1:  ", sorted(result_one), "\nTask 2: ", sorted(result_two))
This is the optimal way!

2021-01-19 20:42 UTC, katemalash commented on pakhai/HW7/task_3_hw7.py
> +             print( "\nCiti in the country - " ,key)
It was required to use the list of cities for each country, not one city

2021-01-19 20:42 UTC, katemalash commented on pakhai/HW7/task_4_hw7.py
> +print("Result: ", new_dict)
Good Decision.

2021-01-21 16:27 UTC, ViktorPakhai commented on pakhai/HW7/task_3_hw7.py
> +             print( "\nCiti in the country - " ,key)
I corrected the code

2021-01-22 11:07 UTC, katemalash approved these changes
Looks good now. You can merge pull-request.

2021-01-22 11:07 UTC, katemalash commented on pakhai/HW7/task_3_hw7.py
> +        print('\nCiti in the country - ', i)
Looks better now

2021-01-22 13:02 UTC, merged