Dovzhyk Volodymyr HW 8
katemalash/Rv-056.PythonCore pull request #77
Opened 2021-01-20 09:39 UTC by ReSpekTeR

2021-01-24 07:59 UTC, katemalash requested changes
Please fix issue with month

2021-01-24 07:59 UTC, katemalash commented on dovzhyk/HW8/hw8_task_1.py
> +print(simpleCalc(enterNum_1,enterNum_2,enterOperation))
Good Way

2021-01-24 07:59 UTC, katemalash commented on dovzhyk/HW8/hw8_task_2.py
> +print(simpleDeposit(depositAmount,period))
Nice and optimized

2021-01-24 07:59 UTC, katemalash commented on dovzhyk/HW8/hw8_task_3.py
> +print(checkData(day,month,year))
Does this solution check the correctness of month?

2021-01-24 07:59 UTC, katemalash commented on dovzhyk/HW8/hw8_task_4.py
> +    if num > 5 and num % 10 == 5 or num > 2 and num % 2 == 0:
Why did you separate this checking?

2021-01-24 07:59 UTC, katemalash commented on dovzhyk/HW8/hw8_task_4.py
> +        print(enter, 'is composite number.')
Decision works. Nice

2021-01-24 07:59 UTC, katemalash commented on dovzhyk/HW8/hw8_task_4.py
> +        for i in range(2,num):
The range could be more optimal, for example, range(2, num // 2 + 1)

2021-01-24 07:59 UTC, katemalash commented on dovzhyk/HW8/hw8_task_5.py
> +        print(is_year_leap(enter))
Nice and optimal decision

2021-01-24 17:00 UTC, ReSpekTeR commented on dovzhyk/HW8/hw8_task_4.py
> +        for i in range(2,num):
Thanks for the tip.

2021-01-24 17:01 UTC, ReSpekTeR commented on dovzhyk/HW8/hw8_task_3.py
> +print(checkData(day,month,year))
No, I miss that moment

2021-01-24 17:24 UTC, ReSpekTeR commented on dovzhyk/HW8/hw8_task_4.py
> +    if num > 5 and num % 10 == 5 or num > 2 and num % 2 == 0:
Hmm. Branching is not needed there at all.
I'll take a look at it!

2021-01-25 21:42 UTC, katemalash approved these changes
Good Job. You can merge pull-request

2021-01-25 21:42 UTC, katemalash commented on dovzhyk/HW8/hw8_task_3.py
> +    print('The date is incorrect')
Looks Good now.

2021-01-29 11:37 UTC, merged