Oleksandr_Tsapin_HW8
katemalash/Rv-056.PythonCore pull request #78
Opened 2021-01-20 16:20 UTC by OleksandrTsapin

2021-01-25 21:50 UTC, katemalash requested changes
Please correct the solution of task with the prime numbers.

2021-01-25 21:50 UTC, katemalash commented on tsapin/HW8/task1.py
> +print(calculator(100,5,'//'))
Good Decision

2021-01-25 21:50 UTC, katemalash commented on tsapin/HW8/task2.py
> +    return initial_balance * (1+annual_interest)**years
nice optimization

2021-01-25 21:50 UTC, katemalash commented on tsapin/HW8/task2.py
> +print(deposit(100,10))
Perfect Decision

2021-01-25 21:50 UTC, katemalash commented on tsapin/HW8/task3.py
> +def date(day, month, year): #date format 'd.m.yyyy'
Just advice: it would be better use `dd.mm.yyyy`

2021-01-25 21:50 UTC, katemalash commented on tsapin/HW8/task3.py
> +    print()
Pretty good decision. You've done it without` date()` function. Nice.

2021-01-25 21:50 UTC, katemalash commented on tsapin/HW8/task4.py
> +    else: return True
This algorithm is not correct. you check only possibility for dividing on 2 and three.

2021-01-25 21:50 UTC, katemalash commented on tsapin/HW8/task5.py
> +    print(is_year_leap(int(input("--> year: "))))
Nice

2021-01-29 20:18 UTC, OleksandrTsapin commented on tsapin/HW8/task3.py
> +def date(day, month, year): #date format 'd.m.yyyy'
Sure. I checked - the app works with dd.mm.yyyy as well. So I'll just change the doc notation.

2021-01-29 20:21 UTC, OleksandrTsapin commented on tsapin/HW8/task3.py
> +def date(day, month, year): #date format 'd.m.yyyy'
Sure. I checked - the app works with dd.mm.yyyy as well. So I'll just change the doc notation.

2021-01-30 19:44 UTC, katemalash approved these changes
Good Job. Now you can merge this pull-request.

2021-01-30 19:44 UTC, katemalash commented on tsapin/HW8/task4.py
> +        print(is_prime(num))
Pretty nice decision!

2021-01-30 19:52 UTC, merged