added homework8
katemalash/Rv-056.PythonCore pull request #88
Opened 2021-01-24 17:20 UTC by Igaross

2021-01-30 20:15 UTC, katemalash requested changes
Please improve two tasks to complete this home work.

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task1.py
> +        return print
Probably you've missed `c`

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task1.py
> +calculator(100, 4, "/")
This is working decision. And it would be better to refactor it to form :
```
    elif c == "*": 
        return  a * b
...
print(calculator(100, 4, "/"))
```

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task2.py
> +    return print(a)
It would be better to return just `a`, not `print(a)`.
But this decision works.

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task3.py
> +        if month >= 2:
Will this code somewhen execute?

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task3.py
> +    import datetime
imports should be placed outside the functions

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task3.py
> +dateTrue()
This decision includes the working code. But a lot of code do nothing. Please delete the obsolete code :-)

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task4.py
> +is_prime(n)
Nice Decision

2021-01-30 20:15 UTC, katemalash commented on Svietlov/homework8/task5.py
> +        if y % 4 == 0:
And what about 1900?

2021-02-02 16:07 UTC, Igaross commented on Svietlov/homework8/task1.py
> +        return print
Yes. Thank you!

2021-02-02 16:07 UTC, Igaross commented on Svietlov/homework8/task1.py
> +calculator(100, 4, "/")
Done.

2021-02-02 16:11 UTC, Igaross commented on Svietlov/homework8/task2.py
> +    return print(a)
Something went wrong and "a" does not print to the console, when I return "a".

2021-02-02 16:24 UTC, Igaross commented on Svietlov/homework8/task3.py
> +        if month >= 2:
This works but does not output "False" :(

2021-02-02 16:24 UTC, Igaross commented on Svietlov/homework8/task3.py
> +    import datetime
Done

2021-02-02 16:26 UTC, Igaross commented on Svietlov/homework8/task3.py
> +dateTrue()
I wanted to complete my first idea in the future... I'll leave it somewhere else)

2021-02-02 16:28 UTC, Igaross commented on Svietlov/homework8/task4.py
> +is_prime(n)
Thank you

2021-02-02 16:31 UTC, Igaross commented on Svietlov/homework8/task5.py
> +        if y % 4 == 0:
fixed

2021-02-02 16:33 UTC, merged