added homework9
katemalash/Rv-056.PythonCore pull request #94
Opened 2021-01-28 14:53 UTC by Igaross

2021-01-31 09:52 UTC, katemalash requested changes
Please refactor tasks 1 - 4.

2021-01-31 09:52 UTC, katemalash commented on Svietlov/homework9/task1/module_task1.py
> +
Please refactor this code so that functions return the result but not print it

2021-01-31 09:52 UTC, katemalash commented on Svietlov/homework9/task1/task1.py
> +fracAB(333, 0.3)
This is right way for current implementation of task 1

2021-01-31 09:52 UTC, katemalash commented on Svietlov/homework9/task3.py
> +
Please define 4 functions: sum, dif, product and fraction inside the calcArg function and return one of this functions, depend on argument. calcArg should have one argument. a and b should be inputed inside the function.

2021-01-31 09:52 UTC, katemalash commented on Svietlov/homework9/task4.py
> +
Tasty sandwiches and good code.

2021-02-02 16:38 UTC, Igaross commented on Svietlov/homework9/task1/module_task1.py
> +
Done

2021-02-02 16:38 UTC, Igaross commented on Svietlov/homework9/task1/task1.py
> +fracAB(333, 0.3)
Thank you

2021-02-02 17:44 UTC, Igaross commented on Svietlov/homework9/task3.py
> +
Done :)

2021-02-02 17:57 UTC, Igaross commented on Svietlov/homework9/task4.py
> +
Thank you :)

2021-02-02 17:58 UTC, merged